### ISSUE TITLE
Zamiana parametrów z resuest.body na REST'owe

### ISSUE THREAD

**Issue by 123kubix123** [impune-pl/projekt-zespolowy#12]
Tylko nie wiem gdzie powinno być GET a gdzie POST w sumie, bo często to nie pobranie danych tylko niby modyfikacja ale mi wszystko jedno i jak najbardziej może być POST /contact/accept i w body id_kontaktu, zarówno jak i GET /contact/:id/accept @impune-pl może ty sie wypowiedz też.
Ważne żeby nigdzie nie było body w żądaniach GET XD

**Comment by therobby** [comment]
Naprawione w commit f478216 (kolejne dwa powstały dzięki mojemu brainfartowi)
/contact/accept lub raczej teraz /contact/:id/accept jest poset.
