### ISSUE TITLE
Można dodać siebie jako kontakt

### ISSUE THREAD

**Issue by 123kubix123** [impune-pl/projekt-zespolowy#13]
A nie powinno
![image](https://user-images.githubusercontent.com/13787550/106358824-d9d15a00-630e-11eb-90d4-3d7910be0370.png)

**Comment by therobby** [comment]
Naprawione w commit f478216
A widział Pan może Messengera? Ja tam często piszę sam do siebie xd
Nie no dobra, faktycznie nie powinno u nas tego być, dodałem sprawdzenie na backend, powinno się teraz nie dać tego zrobić.

**Comment by 123kubix123** [comment]
Problem iz still
![image](https://user-images.githubusercontent.com/13787550/106747359-18735700-6624-11eb-8c53-f81b69618352.png)

**Comment by 123kubix123** [comment]
vry bad

**Comment by therobby** [comment]
problemem była za duża ilość '=' w pewnym if'ie xd Sprawdziłem, u mnie już działa
