### ISSUE TITLE
Można dodać wielokrotnie ten sam kontakt

### ISSUE THREAD

**Issue by 123kubix123** [impune-pl/projekt-zespolowy#14]
Heh
![image](https://user-images.githubusercontent.com/13787550/106358841-f372a180-630e-11eb-87d7-4ace9cbd7d30.png)

**Comment by impune-pl** [comment]
Fix zaraz dodam do bazy, nie wiem czy @therobby nie będzie musiał obsłużyć błędu w backendzie. Żeby zaaplikować fix u siebie wykonajcie poniższy kod:
`ALTER TABLE ONLY public."Contacts"
    ADD CONSTRAINT "AvoidDuplicateContacts" UNIQUE ("userId", "contactId");`

**Comment by therobby** [comment]
Naprawione w commit f478216
Ogółem błędy mam każde handlowane jakoś na backendzie, jak nie są, to jest to błąd i poproszę o nowe issue wtedy xd
Tak czy siak, dodałem sprawdzanie tego też na backendzie.
