### ISSUE TITLE
Nie działa hashowanie hasła

### ISSUE THREAD

**Issue by 123kubix123** [impune-pl/projekt-zespolowy#15]
Plaintext w bazie 
![image](https://user-images.githubusercontent.com/13787550/106358859-14d38d80-630f-11eb-956f-9f51c8aa3dc8.png)

**Comment by therobby** [comment]
Naprawione w commit f478216
Hashowanie było wyłączone w celach łatwiejszego testowania, w finalnej wersji miało zostać włączone. Jeśli jednak aż tak bardzo potrzebujesz hashowania, to proszę bardzo. Kwestia zakomentowania jednej linijki.
