### ISSUE TITLE
Nie ma jak pobrać danych użytkownika

### ISSUE THREAD

**Issue by 123kubix123** [impune-pl/projekt-zespolowy#17]
Np w przypadku pobrania kontaktów:
![image](https://user-images.githubusercontent.com/13787550/106358899-4ba9a380-630f-11eb-8261-7715549d2eb1.png)
są tylko ID a ja potrzebuję numerów tel etc.

**Comment by therobby** [comment]
Naprawione w commit f478216
Teraz /contacts zwraca również informacje dotyczące kontaktu. Informacje dotyczące zalogowanego użytkownika są dostępne pod /user
