### ISSUE TITLE
Gib search function

### ISSUE THREAD

**Issue by 123kubix123** [impune-pl/projekt-zespolowy#20]
POST /contact/find z danymi w stylu {phrase: "test"}
z wyszukiwaniem po fragmiencie maila albo po całym numerze telefunka ^^
Gwerenda: SELECT * FROM Users WHERE Users.email LIKE '%$phrase%' OR Users.phoneNumber LIKE $phrase

**Comment by therobby** [comment]
Dodano szukanie po fragmencie emaila
