### ISSUE TITLE
Nie da się odblokować użytkonika

### ISSUE THREAD

**Issue by 123kubix123** [impune-pl/projekt-zespolowy#23]
JAk ban to perm od razu?
Cy jak?

**Comment by impune-pl** [comment]
Brak możliwości odblokowania użytkonika wynika z braku użytkoników w systemie. Powodem jest przeznaczenie systemu dla ludzi, nie dla koni.

**Comment by impune-pl** [comment]
A tak na serio, to baza nie blokuje usuwania kontaktów, więc jest to kwestia utworzenia endpointa wykonującego kwerendę DELETE.
Dobrze by było jakby endpoint sprawdzał przed wykonaniem czy użytkownik usuwający jest celem kontaktu (czy id użytkownika jest równe zawartości kolumny contactId)

**Comment by therobby** [comment]
albo dodać zwyczajnie opcję odblokowania, w trakcie czego jestem aktualnie

**Comment by therobby** [comment]
Opcja odblokowania teraz istnieje i powinna działać
