### ISSUE TITLE
Nie da się odrzucić jak ktoś cię do znajomych dodał

### ISSUE THREAD

**Issue by 123kubix123** [impune-pl/projekt-zespolowy#24]
A fajnie by było żeby nie dało się zaspamowac requestami

**Comment by impune-pl** [comment]
Sugerowałbym w takim wypadku zrobienie tak:
skoro kontakt w jednostronny (między dodającym a dodawanym) jest prośbą o dodanie, to kontakt jednostronny z isBlocked=true niech będzie odrzuconą prośbą o dodanie.

**Comment by 123kubix123** [comment]
Znaczy generalnie ja na froncie zrobiłem 2 listy kontakty zaakceptowane i requesty o dodanie.
W zaakceptowae mają isAccepted === true i mogą mieć isBlocked na true i false (zmienia się guzik)
a w requesty nie mają accepta i fajnie by było dać opcję usunięcia requesta po prostu tak żeby nie wisiał

**Comment by therobby** [comment]
w sumie mogę dać /contact/:id/dismiss czy coś takiego, gdzie jak kontakt nie jest zaakceptowany (czyli jest to zaproszenie) to można go zwyczajnie odrzucić i usunąć z bd, wieczorem do tego siądę

**Comment by therobby** [comment]
Opcja została dodana

**Comment by 123kubix123** [comment]
Tak ale nie działa:
![image](https://user-images.githubusercontent.com/13787550/106747678-8881dd00-6624-11eb-95a4-8de2fbdd6e86.png)
![image](https://user-images.githubusercontent.com/13787550/106747702-8e77be00-6624-11eb-9d8d-4210f4147030.png)
![image](https://user-images.githubusercontent.com/13787550/106747733-96cff900-6624-11eb-90a6-c01c28ab931e.png)

**Comment by therobby** [comment]
a jakie id dajesz? bo powinno być id kontaktu, w sensie tabeli, a nie użytkownika

**Comment by 123kubix123** [comment]
Uguem to jest problem że daje dismiss na true ale spoko XD

**Comment by therobby** [comment]
naprawione w ostatnim commit
