### ISSUE TITLE
Oh my where is message ID, mamma mija jak sortować?

### ISSUE THREAD

**Issue by 123kubix123** [impune-pl/projekt-zespolowy#27]
Dej id wiadomości bo nie wiem jaka była ostatnia 😁
![image](https://user-images.githubusercontent.com/13787550/106597368-9c5f0d80-6556-11eb-873f-91e13d1da0da.png)

Czy wiadomości będą w jakiejś konkretnej kolejności (najlepsze by było od najstarszych do najnowszych)
eg:
messages:[
{
 id: 100,
...
},
{
 id: 101,
...
},
{
 id: 102,
...
}
]

**Comment by therobby** [comment]
ej, ale to weszło w commicie 4bbc2c7a64f246e22b91c81e9bdf1fc6c713a885

**Comment by therobby** [comment]
Upewniłem się jeszcze raz czy to jest, ale potwierdziło to tylko, że jest i działa, także miłej zabawy w sortowanie xd
