### ISSUE TITLE
Akceptowanie kontaktu nie działa

### ISSUE THREAD

**Issue by 123kubix123** [impune-pl/projekt-zespolowy#30]
![image](https://user-images.githubusercontent.com/13787550/106748045-f7f7cc80-6624-11eb-8755-390c06bf8ba9.png)
![image](https://user-images.githubusercontent.com/13787550/106748072-fdedad80-6624-11eb-9115-983b073b702b.png)
![image](https://user-images.githubusercontent.com/13787550/106748099-0645e880-6625-11eb-9f9e-a99d2472e736.png)

**Comment by 123kubix123** [comment]
![image](https://user-images.githubusercontent.com/13787550/106748216-2f667900-6625-11eb-9c7a-c5cd8db02f29.png)
to ma być danego kontaktu - contactId czy id z tabeli Contacts?

**Comment by therobby** [comment]
z tabeli

**Comment by 123kubix123** [comment]
Uguem to jest problem że daje accept na true ale spoko XD

**Comment by therobby** [comment]
naprawione w ostatnim commit
